### PR TITLE
add metrics to CAS

### PR DESCRIPTION
**Pull request by gvelez17**
# add metrics to CAS - #PLAT-640, #670

## Description

Add metrics package to CAS and sample metrics for consumption by prometheus.

This will enable promQL alerting queries to trigger discord or other external alerts from our grafana dashboards.

## How Has This Been Tested?

Describe the tests that you ran to verify your changes. Provide instructions for reproduction.

- [ ] Test A (e.g. Test A - New test that ... ran in local, docker, and dev unstable.)
- [ ] Test B

## Definition of Done

Before submitting this PR, please make sure:

- [ ] The work addresses the description and outcomes in the issue
- [ ] I have added relevant tests for new or updated functionality
- [ ] My code follows conventions, is well commented, and easy to understand
- [ ] My code builds and tests pass without any errors or warnings
- [ ] I have tagged the relevant reviewers
- [ ] I have updated the READMEs of affected packages
- [ ] I have made corresponding changes to the documentation
- [ ] The changes have been communicated to interested parties

## References:

Please list relevant documentation (e.g. tech specs, articles, related work etc.) relevant to this change, and note if the documentation has been updated.

### CODE REVIEW

**Comment by gvelez17** [comment]
So in js-ceramic, we set up the config here https://github.com/ceramicnetwork/js-ceramic/blob/c791499a33f888f7a2cbe1415ac6c9bc451bcbe8/packages/cli/src/daemon-config.ts#L310

Do we have something analogous in CAS @stephhuynh18 ?

**Comment by stephhuynh18** [comment]
https://www.npmjs.com/package/node-config-ts is used for the config. So any configs you need should be added here: https://github.com/ceramicnetwork/ceramic-anchor-service/tree/develop/config. We don't have anything as structured as js-ceramic.

**Review by stephhuynh18 — COMMENTED** [review]
Looks pretty good to me. Just have a few cosmetic changes that i can do (ex. removing console logs, formatting) ~~and I'm going to move the test to the anchor-service test instead.~~

**Comment by stephhuynh18** [comment]
Request reviews as I wrote the last commit

**Review by ukstv — APPROVED** [review]

**Pull request merged**
