### PR TITLE
Add Admin API cloudwatch metrics

### PR DESCRIPTION
**Pull request by gvelez17**
# Add Admin API cloudwatch metrics - #PLAT-1070

## Description

This PR generates metrics on register and verify, and creates the metrics class for reuse

## How Has This Been Tested?

- [X] Ran on dev and successfully generated metrics for verify and register
image

https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#metricsV2:graph=~(metrics~(~(~(expression~'SELECT*20SUM*28*22cas_admin-api-dev_register*22*29*20FROM*20CeramicAnchorService~label~'Query1~id~'q1))~(~'CeramicAnchorService~'api-gateway-dev-launch~(id~'m1))~(~'.~'cas_admin-api-dev_register~(id~'m2))~(~'.~'cas_admin-api-dev_verify~(id~'m3)))~view~'timeSeries~stacked~false~region~'us-east-2~start~'-PT1H~end~'P0D~stat~'Sum~period~300~title~'API*20Gateway*20Admin*20Auth*20Actions);query=~'*7bCeramicAnchorService*7d

I would like to merge this, and then I need to discuss how to access the context in the handler - I did not see a request object in the handler, so maybe I need to instantiate it again there.

## Definition of Done

Before submitting this PR, please make sure:

- [ ] The work addresses the description and outcomes in the issue
- [ ] I have added relevant tests for new or updated functionality
- [ ] My code follows conventions, is well commented, and easy to understand
- [ ] My code builds and tests pass without any errors or warnings
- [ ] I have tagged the relevant reviewers
- [ ] I have updated the READMEs of affected packages
- [ ] I have made corresponding changes to the documentation
- [ ] The changes have been communicated to interested parties

## References:

Please list relevant documentation (e.g. tech specs, articles, related work etc.) relevant to this change, and note if the documentation has been updated.

### CODE REVIEW

**Comment by gvelez17** [comment]
The test error is maybe unrelated?  

```
FAIL auth/src/__tests__/integration.spec.ts
  ● Test suite failed to run

    Cannot find module 'luxon' from 'auth/src/__tests__/integration.spec.ts'

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:425:11)
          at async Promise.all (index 0)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From auth/src/__tests__/integration.spec.ts.

          at async Promise.all (index 2)
          
          ```
Is this somehow because of my code?

**Comment by v-stickykeys** [comment]
I'm not sure what these metrics mean.
What is `cas_admin-api-dev_register` and `cas_admin-api-dev_verify`?
What is Query1?
What is `api-gateway-dev-launch`?

**Comment by gvelez17** [comment]
@v-stickykeys  so cas_admin-api-dev_register is marked whenever someone registers a did
I could change it to a better name, like     `cas_admin_dev_ register_did`

cas_admin-api-dev_verify. is marked whenever someone sends a verification email to get an OTP
I could change it to.    `cas_admin_dev_request_otp`

the "launch" one was for testing, I can delete that manually to avoid confusion.

**Comment by gvelez17** [comment]
will change to

```cas_auth_did_registration_total
cas_auth_otp_request_total```

**Comment by gvelez17** [comment]
out of date, closing

**Pull request closed without merging**
