### PR TITLE
feat: do not write to ipfs

### PR DESCRIPTION
**Pull request by smrz2001**
This PR puts IPFS writes behind a feature flag. We can add more things for operationalizing CAS to this PR, if needed (e.g. more metrics).

### CODE REVIEW

**Review by stbrody — APPROVED** [review]
why am I having deja vu?  Didn't we do this already?

**Review by stbrody — COMMENTED** [review]
also lets make sure to set that ENV var on all our environments before merging this, or else we risk changing behavior immediately.

Should we maybe invert the condition so the default behavior stays the same as it is now, and it requires an active config change to change the behavior and stop using ipfs?

**Comment by smrz2001** [comment]
> why am I having deja vu?  Didn't we do this already?

Lolol yes, we did, but in the scaling prototype PR, which is on hold. I pulled this change from that PR. 

> also lets make sure to set that ENV var on all our environments before merging this, or else we risk changing behavior immediately.

Good point, will do. 

> Should we maybe invert the condition so the default behavior stays the same as it is now, and it requires an active config change to change the behavior and stop using ipfs?

Honestly, I'd rather add the new variable to the envs than have a double negative haha.

`CAS_DONT_USE_IPFS_STORAGE = false` will break my brain...

https://tenor.com/bDsu7.gif

**Comment by 3benbox** [comment]
> > Should we maybe invert the condition so the default behavior stays the same as it is now, and it requires an active config change to change the behavior and stop using ipfs?
> 
> Honestly, I'd rather add the new variable to the envs than have a double negative haha.
> 
> `CAS_DONT_USE_IPFS_STORAGE = false` will break my brain...

How about a metric when are successfully loaded on IPFS, in addition to the current failure metric.

That way we can track that ipfs loads are still happening where we expect them to be.

**Review by 3benbox — APPROVED** [review]
lgtm!

**Comment by smrz2001** [comment]
> How about a metric when are successfully loaded on IPFS, in addition to the current failure metric.
> 
> That way we can track that ipfs loads are still happening where we expect them to be.

Yeah, I don't mind that. I can add new metrics for IPFS record and CAR file storage.

**Comment by smrz2001** [comment]
FYI, @stbrody @ukstv @stephhuynh18, I haven't added the new env var to any of the environments. Since the deadline for deprecating CAS IPFS is coming up next week anyway, IMO we can leave IPFS disabled by default.

If the PR looks good, we can merge to Dev/QA. Then Monday we can merge to Clay, watch a couple of days, then plan to merge to Prod. If something blows up, we can add the env var and re-enable IPFS quickly.

**Comment by stbrody** [comment]
Sounds good, definitely let's get this merged ASAP so it can start burning in and we can see if any problems show up in our tests.

I do still think we should probably spend some time looking into the merkle car errors on prod before we deploy to prod: https://linear.app/3boxlabs/issue/WS1-1608/no-merkle-car-found-for-anchor-errors-are-common-on-prod-cas.  CC @ukstv @christianlavoie

**Review by stephhuynh18 — APPROVED** [review]

**Pull request merged**
