### PR TITLE
ci: remove image build and deploy

### PR DESCRIPTION
**Pull request by valmack**
Using dockerhub instead for now

### CODE REVIEW

**Comment by oed** [comment]
Sorry I don't have the full context here. What are these being replaced with?

**Comment by valmack** [comment]
@oed docker hub images here: https://hub.docker.com/repository/docker/ceramicnetwork/ceramic-anchor-service

**Comment by stbrody** [comment]
I also don't really feel like I have enough context to meaningfully sign off on this.  Maybe @zachferland does, or maybe no one besides you really does?  In which case I guess you should just push without review?  Hopefully soon we'll hire a backend engineer and have another person on the team who's familiar with how our infra is managed...

**Comment by valmack** [comment]
@stbrody yeah that's fair. Just added you because it was relevant to me wanting to block merges into CAS develop branch. I'm going to merge this because it is just dead code at this point and there's no point in running a CI job that we aren't using.

**Pull request merged**
