### PR TITLE
Added HireNodes Gitcoin to the ipAllowlist

### PR DESCRIPTION
**Pull request by 3benbox**
Closes CDB-2380

## Description

Added ip address.

## How Has This Been Tested?

Ran on dev

## Definition of Done

Apply to prod

### CODE REVIEW

**Review by smrz2001 — APPROVED** [review]
🚀

**Review by gvelez17 — APPROVED** [review]

**Comment by gvelez17** [comment]
hey @3benbox not sure why the test didn't pass but we should merge this?

**Comment by 3benbox** [comment]
> hey @3benbox not sure why the test didn't pass but we should merge this?

I updated the account to the large usage plan and that seems to be working. I'd rather keep them on a plan and only bypass if necessary.

**Review by gvelez17 — APPROVED** [review]

**Comment by gvelez17** [comment]
ugh this is outdated and giving issues with the lockfile, going to restart it fresh to just add the one line

**Pull request closed without merging**
